In [1]:
import pandas as pd
import math
%run get_results.ipynb
import statistics

In [2]:
test_stack = pd.read_excel('DB/StackTest.xlsx')
test_stack

,Queries,w2v_res1,w2v_res2,w2v_res3,w2v_res4,w2v_res5,tfidf_res1,tfidf_res2,tfidf_res3,tfidf_res4,tfidf_res5
0,Using IF function in Pandas dataframe,0,1,1,1,1,0,1,0,0,0
1,How to send WhatsApp message each minute,0,0,0,0,0,0,0,0,0,1
2,Parsing a JSON list into a normal string?,0,0,0,0,0,0,1,0,0,0
3,how to get version python,0,0,0,0,0,0,0,0,0,0
4,Combining multiple columns into one,1,1,1,0,0,0,0,1,1,1
5,extracting features from dataframe,1,0,1,0,1,0,0,0,0,0
6,Grouping NLTK entities,0,0,0,0,0,0,0,0,0,0
7,delete a list from collection of list,0,1,0,0,0,1,0,0,0,0
8,get api google maps,0,0,1,0,1,1,1,0,0,0
9,add guassian noise to a numpy array,0,1,0,0,0,0,0,0,0,0
10,unable to establish SSL connection,0,1,1,0,0,1,1,0,0,0
11,create new project in django,1,1,1,1,1,1,1,0,0,0
12,can not pip install a branch,0,0,1,0,0,1,0,0,0,0
13,can not use scrapy on Apple M1 chip,0,0,0,0,0,0,0,0,0,0
14,convert text to image,0,0,0,0,0,0,0,0,0,0
15,calculate distance between two points,1,1,1,0,1,1,0,1,1,0
16,remove duplicates items in array,0,1,0,0,0,0,0,0,0,0
17,how to send message using telepot,0,0,0,0,0,0,0,0,0,0
18,get current time zone,1,1,1,1,1,1,0,0,1,0
19,problem in import rest framework,1,1,1,1,1,1,1,0,0,1
20,get timestamp in UNIX,1,1,1,1,1,0,1,1,1,1
21,how to add column in pandas,1,1,1,0,1,1,0,0,0,1
22,How to set value to pandas crosstab?,0,0,0,0,0,1,0,0,0,0
23,How to update a variable?,0,1,0,1,0,0,0,1,0,0
24,error: fit() missing argument,1,1,1,0,0,0,0,0,0,0
25,how to make a test on regex?,0,0,0,0,0,0,0,0,0,0
26,try web scraping to get text,1,1,1,1,1,0,1,1,1,1
27,convert int in string,0,1,0,0,0,0,0,0,0,0
28,Classify music according to bpm,0,0,0,0,0,0,0,0,0,0
29,How to run a script on Linux?,1,0,0,0,1,1,0,0,0,0
30,How to join list of strings,1,0,0,0,0,0,0,0,0,0
31,How to write to csv file,1,1,1,1,1,1,1,1,1,1
32,count rows where column is NaN,0,1,0,0,1,1,0,0,0,0
33,get all index from boolean list,1,1,1,0,0,0,0,0,0,0
34,split on a numerical character,0,0,0,0,0,0,0,0,0,0
35,sorting a multindex dataframe,1,1,0,0,1,0,0,0,0,0
36,how to print variable,0,0,1,1,0,1,0,1,0,1
37,sum values in column,0,1,1,1,1,1,0,1,0,0
38,how to order value in array,0,0,0,0,0,0,0,0,0,1
39,save image with added mask,1,0,0,1,0,1,1,1,0,0
40,greatest number in list of list,0,0,0,0,1,1,1,0,0,0
41,how to add legend for picture,1,0,0,0,0,0,0,0,0,0
42,how to setup virtual enviroment,1,1,1,0,0,0,0,0,0,1
43,remove stopwords with regular expressions,0,0,0,0,0,0,0,1,1,0
44,how to use min() function for floats,0,0,0,0,0,0,0,0,0,0
45,how to add checkbox to a button,0,0,0,0,0,0,0,0,0,0
46,importing a pygame event into another script,0,0,0,0,0,0,0,0,0,0
47,pip install web3 is not working,0,0,0,0,0,0,0,0,0,0
48,parsing data from XML into excel,0,1,1,1,0,1,0,0,0,0
49,how to get ssid,0,0,0,0,0,1,0,0,0,0

In [3]:
data = [test_stack['Queries'],test_stack['w2v_res1'],test_stack['w2v_res2'],test_stack['w2v_res3'],test_stack['w2v_res4'],test_stack['w2v_res5']]
headers = ['Queries','w2v_res1','w2v_res2','w2v_res3','w2v_res4','w2v_res5']

test_stack_w2v_evaluated = pd.concat(data, axis=1, keys=headers)

test_stack_w2v_evaluated

,Queries,w2v_res1,w2v_res2,w2v_res3,w2v_res4,w2v_res5
0,Using IF function in Pandas dataframe,0,1,1,1,1
1,How to send WhatsApp message each minute,0,0,0,0,0
2,Parsing a JSON list into a normal string?,0,0,0,0,0
3,how to get version python,0,0,0,0,0
4,Combining multiple columns into one,1,1,1,0,0
5,extracting features from dataframe,1,0,1,0,1
6,Grouping NLTK entities,0,0,0,0,0
7,delete a list from collection of list,0,1,0,0,0
8,get api google maps,0,0,1,0,1
9,add guassian noise to a numpy array,0,1,0,0,0
10,unable to establish SSL connection,0,1,1,0,0
11,create new project in django,1,1,1,1,1
12,can not pip install a branch,0,0,1,0,0
13,can not use scrapy on Apple M1 chip,0,0,0,0,0
14,convert text to image,0,0,0,0,0
15,calculate distance between two points,1,1,1,0,1
16,remove duplicates items in array,0,1,0,0,0
17,how to send message using telepot,0,0,0,0,0
18,get current time zone,1,1,1,1,1
19,problem in import rest framework,1,1,1,1,1
20,get timestamp in UNIX,1,1,1,1,1
21,how to add column in pandas,1,1,1,0,1
22,How to set value to pandas crosstab?,0,0,0,0,0
23,How to update a variable?,0,1,0,1,0
24,error: fit() missing argument,1,1,1,0,0
25,how to make a test on regex?,0,0,0,0,0
26,try web scraping to get text,1,1,1,1,1
27,convert int in string,0,1,0,0,0
28,Classify music according to bpm,0,0,0,0,0
29,How to run a script on Linux?,1,0,0,0,1
30,How to join list of strings,1,0,0,0,0
31,How to write to csv file,1,1,1,1,1
32,count rows where column is NaN,0,1,0,0,1
33,get all index from boolean list,1,1,1,0,0
34,split on a numerical character,0,0,0,0,0
35,sorting a multindex dataframe,1,1,0,0,1
36,how to print variable,0,0,1,1,0
37,sum values in column,0,1,1,1,1
38,how to order value in array,0,0,0,0,0
39,save image with added mask,1,0,0,1,0
40,greatest number in list of list,0,0,0,0,1
41,how to add legend for picture,1,0,0,0,0
42,how to setup virtual enviroment,1,1,1,0,0
43,remove stopwords with regular expressions,0,0,0,0,0
44,how to use min() function for floats,0,0,0,0,0
45,how to add checkbox to a button,0,0,0,0,0
46,importing a pygame event into another script,0,0,0,0,0
47,pip install web3 is not working,0,0,0,0,0
48,parsing data from XML into excel,0,1,1,1,0
49,how to get ssid,0,0,0,0,0

In [4]:
data = [test_stack['Queries'],test_stack['tfidf_res1'],test_stack['tfidf_res2'],test_stack['tfidf_res3'],test_stack['tfidf_res4'],test_stack['tfidf_res5']]
headers = ['Queries','tfidf_res1','tfidf_res2','tfidf_res3','tfidf_res4','tfidf_res5']

test_stack_tfidf_evaluated = pd.concat(data, axis=1, keys=headers)

test_stack_tfidf_evaluated

,Queries,tfidf_res1,tfidf_res2,tfidf_res3,tfidf_res4,tfidf_res5
0,Using IF function in Pandas dataframe,0,1,0,0,0
1,How to send WhatsApp message each minute,0,0,0,0,1
2,Parsing a JSON list into a normal string?,0,1,0,0,0
3,how to get version python,0,0,0,0,0
4,Combining multiple columns into one,0,0,1,1,1
5,extracting features from dataframe,0,0,0,0,0
6,Grouping NLTK entities,0,0,0,0,0
7,delete a list from collection of list,1,0,0,0,0
8,get api google maps,1,1,0,0,0
9,add guassian noise to a numpy array,0,0,0,0,0
10,unable to establish SSL connection,1,1,0,0,0
11,create new project in django,1,1,0,0,0
12,can not pip install a branch,1,0,0,0,0
13,can not use scrapy on Apple M1 chip,0,0,0,0,0
14,convert text to image,0,0,0,0,0
15,calculate distance between two points,1,0,1,1,0
16,remove duplicates items in array,0,0,0,0,0
17,how to send message using telepot,0,0,0,0,0
18,get current time zone,1,0,0,1,0
19,problem in import rest framework,1,1,0,0,1
20,get timestamp in UNIX,0,1,1,1,1
21,how to add column in pandas,1,0,0,0,1
22,How to set value to pandas crosstab?,1,0,0,0,0
23,How to update a variable?,0,0,1,0,0
24,error: fit() missing argument,0,0,0,0,0
25,how to make a test on regex?,0,0,0,0,0
26,try web scraping to get text,0,1,1,1,1
27,convert int in string,0,0,0,0,0
28,Classify music according to bpm,0,0,0,0,0
29,How to run a script on Linux?,1,0,0,0,0
30,How to join list of strings,0,0,0,0,0
31,How to write to csv file,1,1,1,1,1
32,count rows where column is NaN,1,0,0,0,0
33,get all index from boolean list,0,0,0,0,0
34,split on a numerical character,0,0,0,0,0
35,sorting a multindex dataframe,0,0,0,0,0
36,how to print variable,1,0,1,0,1
37,sum values in column,1,0,1,0,0
38,how to order value in array,0,0,0,0,1
39,save image with added mask,1,1,1,0,0
40,greatest number in list of list,1,1,0,0,0
41,how to add legend for picture,0,0,0,0,0
42,how to setup virtual enviroment,0,0,0,0,1
43,remove stopwords with regular expressions,0,0,1,1,0
44,how to use min() function for floats,0,0,0,0,0
45,how to add checkbox to a button,0,0,0,0,0
46,importing a pygame event into another script,0,0,0,0,0
47,pip install web3 is not working,0,0,0,0,0
48,parsing data from XML into excel,1,0,0,0,0
49,how to get ssid,1,0,0,0,0

In [5]:
queries = test_stack['Queries']
queries

0            Using IF function in Pandas dataframe
1         How to send WhatsApp message each minute
2        Parsing a JSON list into a normal string?
3                        how to get version python
4              Combining multiple columns into one
5               extracting features from dataframe
6                           Grouping NLTK entities
7            delete a list from collection of list
8                              get api google maps
9              add guassian noise to a numpy array
10              unable to establish SSL connection
11                    create new project in django
12                    can not pip install a branch
13             can not use scrapy on Apple M1 chip
14                           convert text to image
15           calculate distance between two points
16                remove duplicates items in array
17               how to send message using telepot
18                           get current time zone
19                problem in import rest framework
20                           get timestamp in UNIX
21                     how to add column in pandas
22            How to set value to pandas crosstab?
23                       How to update a variable?
24                   error: fit() missing argument
25                    how to make a test on regex?
26                    try web scraping to get text
27                           convert int in string
28                 Classify music according to bpm
29                   How to run a script on Linux?
30                     How to join list of strings
31                        How to write to csv file
32                  count rows where column is NaN
33                 get all index from boolean list
34                  split on a numerical character
35                   sorting a multindex dataframe
36                           how to print variable
37                            sum values in column
38                     how to order value in array
39                      save image with added mask
40                 greatest number in list of list
41                   how to add legend for picture
42                 how to setup virtual enviroment
43       remove stopwords with regular expressions
44            how to use min() function for floats
45                 how to add checkbox to a button
46    importing a pygame event into another script
47                 pip install web3 is not working
48                parsing data from XML into excel
49                                 how to get ssid
Name: Queries, dtype: object

In [8]:
def create_confusion_matrix(test_evaluation):
    
    tp = 0 
    fp = 0
    tn = 0
    fn = 0 
    
    for rowIndex, row in test_evaluation.iterrows(): #iterate over rows
        for columnIndex, value in row.items():
            if value == 'tp':
                tp = tp + 1
            if value == 'fp':
                fp = fp + 1
            if value == 'tn':
                tn = tn + 1
            if value == 'fn':
                fn = fn  + 1
                
    d = {'Relevant': [tp, fn], 'Non_relevant': [fp, tn]}
    
    confusion_matrix = pd.DataFrame(data = d, index=['Retrieved','Not_retrieved'])
    
    precision = tp/ (tp+fp)
    #print('prec: ',precision)
    recall = tp / (tp+fn)
    #print('recall: ', recall)
    #f1 calcolato con valore parametri beta = 1 e alpha = 1/2
    f1score = (2*precision*recall) / (precision+recall)
    
    return (confusion_matrix,precision,recall,f1score)

In [9]:
def calculate_median(queries,tech):
    
    similarity_scores = []
    
    for q in queries:
        
        if tech == 'w2v':
            results = w2v_stack_result(q)
        else:
            results = tfidf_stack_result(q)
        #creiamo una lista con solo i valori di similarità di ogni primo risultato per query
        sim_value = results[0][1]
        
        similarity_scores.append(sim_value)
    
    median = statistics.median(similarity_scores)
    
    return median

In [10]:
def create_test_table(queries, tech, median):
    
    res_ground_truth = []
    
    for q in queries:
        if tech == 'w2v':
            results = w2v_stack_result(q)
        else:
            results = tfidf_stack_result(q)
        i = 0 
        
        res_q = [0,0,0,0,0]
        
        for r in results:
            sim_value = r[1]
            
            if sim_value >= median:
                res_q[i] = 1
            else:
                res_q[i] = 0
                    
            i = i+1
        res_ground_truth.append(res_q)
        
    data = res_ground_truth 
    
    #print(data)
    test_df = pd.DataFrame.from_records(data)
 
    # specifying column names
    test_df.columns = ['Res1', 'Res2', 'Res3','Res4','Res5']
    
    test_df = test_df.assign(queries=pd.Series(queries).values)
    
    return test_df

In [11]:
def create_evaluation_table(test_results, test_evaluated):
    data = []
    #Ciclo sul df che contiene i risultati del modello 
    for index,row in test_results.iterrows():
        #Lista di risultati valutati personalmente
        r_evaluated = test_evaluated.iloc[index]
        #print('r_evaluated:' , r_evaluated)
        
        final_res = ['','','','','']
        i = 1
        for r in row:
            if (isinstance(r, int)):
                #print('r_evaluated[i]: ', r_evaluated[i] )
                #Se r è 1 vuol dire che per il modello il record è stato registrato come rilevante
                if r == 1:
                    if r == r_evaluated[i]:           
                        #True positive
                        final_res[i-1] = 'tp'
                    else:
                        #False positive
                        final_res[i-1] = 'fp'
                else:
                    if r == r_evaluated[i]:
                        #True negative
                        final_res[i-1] = 'tn'
                    else:
                        #False negative
                        final_res[i-1] = 'fn'

                i = i+1
        data.append(final_res)
        
    #print(data)
    final_df = pd.DataFrame.from_records(data)
 
    # specifying column names
    final_df.columns = ['Res1', 'Res2', 'Res3','Res4','Res5']
    
    final_df = final_df.assign(queries=pd.Series(queries).values)
    
    return final_df

In [15]:
median_w2v = calculate_median(queries,'w2v')

median_tfidf = calculate_median(queries,'tfidf')

print('Median w2v: ' + str(median_w2v) + '\n' + 'Median tfidf: ' + str(median_tfidf))

Median w2v: 0.8521894710458869
Median tfidf: 0.5800834283081819

In [16]:
w2v_test_results = create_test_table(queries,'w2v',median_w2v)

w2v_test_results = w2v_test_results[['queries', 'Res1','Res2','Res3','Res4','Res5']]

w2v_test_results

                                         queries  Res1  Res2  Res3  Res4  Res5
0          Using IF function in Pandas dataframe     1     1     1     1     1
1       How to send WhatsApp message each minute     0     0     0     0     0
2      Parsing a JSON list into a normal string?     1     0     0     0     0
3                      how to get version python     0     0     0     0     0
4            Combining multiple columns into one     1     1     1     1     1
5             extracting features from dataframe     0     0     0     0     0
6                         Grouping NLTK entities     0     0     0     0     0
7          delete a list from collection of list     1     1     1     0     0
8                            get api google maps     0     0     0     0     0
9            add guassian noise to a numpy array     0     0     0     0     0
10            unable to establish SSL connection     0     0     0     0     0
11                  create new project in django     1     1     1     1     1
12                  can not pip install a branch     1     1     1     1     1
13           can not use scrapy on Apple M1 chip     0     0     0     0     0
14                         convert text to image     1     0     0     0     0
15         calculate distance between two points     1     1     1     1     0
16              remove duplicates items in array     1     1     0     0     0
17             how to send message using telepot     0     0     0     0     0
18                         get current time zone     0     0     0     0     0
19              problem in import rest framework     0     0     0     0     0
20                         get timestamp in UNIX     1     1     1     0     0
21                   how to add column in pandas     1     1     1     1     1
22          How to set value to pandas crosstab?     1     1     1     1     1
23                     How to update a variable?     0     0     0     0     0
24                 error: fit() missing argument     0     0     0     0     0
25                  how to make a test on regex?     0     0     0     0     0
26                  try web scraping to get text     1     0     0     0     0
27                         convert int in string     1     1     1     1     1
28               Classify music according to bpm     0     0     0     0     0
29                 How to run a script on Linux?     0     0     0     0     0
30                   How to join list of strings     1     1     1     1     1
31                      How to write to csv file     1     1     1     1     1
32                count rows where column is NaN     1     1     1     1     1
33               get all index from boolean list     0     0     0     0     0
34                split on a numerical character     0     0     0     0     0
35                 sorting a multindex dataframe     1     1     1     1     1
36                         how to print variable     1     0     0     0     0
37                          sum values in column     1     1     1     1     1
38                   how to order value in array     0     0     0     0     0
39                    save image with added mask     0     0     0     0     0
40               greatest number in list of list     1     1     1     1     1
41                 how to add legend for picture     0     0     0     0     0
42               how to setup virtual enviroment     0     0     0     0     0
43     remove stopwords with regular expressions     1     0     0     0     0
44          how to use min() function for floats     0     0     0     0     0
45               how to add checkbox to a button     1     0     0     0     0
46  importing a pygame event into another script     0     0     0     0     0
47               pip install web3 is not working     1     1     1     1     1
48              parsing data from XML into excel     1     0     0     0     0
49                               how to get ssid     0     0     0     0     0

In [17]:
tfidf_test_results = create_test_table(queries,'tfidf',median_tfidf)

tfidf_test_results

    Res1  Res2  Res3  Res4  Res5                                       queries
0      1     0     0     0     0         Using IF function in Pandas dataframe
1      0     0     0     0     0      How to send WhatsApp message each minute
2      0     0     0     0     0     Parsing a JSON list into a normal string?
3      0     0     0     0     0                     how to get version python
4      0     0     0     0     0           Combining multiple columns into one
5      0     0     0     0     0            extracting features from dataframe
6      0     0     0     0     0                        Grouping NLTK entities
7      0     0     0     0     0         delete a list from collection of list
8      1     0     0     0     0                           get api google maps
9      0     0     0     0     0           add guassian noise to a numpy array
10     0     0     0     0     0            unable to establish SSL connection
11     0     0     0     0     0                  create new project in django
12     1     0     0     0     0                  can not pip install a branch
13     0     0     0     0     0           can not use scrapy on Apple M1 chip
14     1     0     0     0     0                         convert text to image
15     1     1     1     0     0         calculate distance between two points
16     1     1     0     0     0              remove duplicates items in array
17     1     0     0     0     0             how to send message using telepot
18     1     0     0     0     0                         get current time zone
19     1     1     0     0     0              problem in import rest framework
20     1     1     1     0     0                         get timestamp in UNIX
21     1     0     0     0     0                   how to add column in pandas
22     1     0     0     0     0          How to set value to pandas crosstab?
23     0     0     0     0     0                     How to update a variable?
24     0     0     0     0     0                 error: fit() missing argument
25     0     0     0     0     0                  how to make a test on regex?
26     1     1     0     0     0                  try web scraping to get text
27     1     1     1     0     0                         convert int in string
28     0     0     0     0     0               Classify music according to bpm
29     1     0     0     0     0                 How to run a script on Linux?
30     0     0     0     0     0                   How to join list of strings
31     1     1     1     0     0                      How to write to csv file
32     1     1     1     0     0                count rows where column is NaN
33     1     0     0     0     0               get all index from boolean list
34     0     0     0     0     0                split on a numerical character
35     0     0     0     0     0                 sorting a multindex dataframe
36     1     0     0     0     0                         how to print variable
37     1     1     1     0     0                          sum values in column
38     0     0     0     0     0                   how to order value in array
39     0     0     0     0     0                    save image with added mask
40     1     0     0     0     0               greatest number in list of list
41     1     1     1     0     0                 how to add legend for picture
42     0     0     0     0     0               how to setup virtual enviroment
43     0     0     0     0     0     remove stopwords with regular expressions
44     0     0     0     0     0          how to use min() function for floats
45     1     1     1     0     0               how to add checkbox to a button
46     0     0     0     0     0  importing a pygame event into another script
47     1     1     1     0     0               pip install web3 is not working
48     1     0     0     0     0              parsing data from XML into excel
49     0     0     0     0     0                               how to get ssid

In [18]:
tfidf_test_results = tfidf_test_results[['queries', 'Res1','Res2','Res3','Res4','Res5']]

tfidf_test_results

                                         queries  Res1  Res2  Res3  Res4  Res5
0          Using IF function in Pandas dataframe     1     0     0     0     0
1       How to send WhatsApp message each minute     0     0     0     0     0
2      Parsing a JSON list into a normal string?     0     0     0     0     0
3                      how to get version python     0     0     0     0     0
4            Combining multiple columns into one     0     0     0     0     0
5             extracting features from dataframe     0     0     0     0     0
6                         Grouping NLTK entities     0     0     0     0     0
7          delete a list from collection of list     0     0     0     0     0
8                            get api google maps     1     0     0     0     0
9            add guassian noise to a numpy array     0     0     0     0     0
10            unable to establish SSL connection     0     0     0     0     0
11                  create new project in django     0     0     0     0     0
12                  can not pip install a branch     1     0     0     0     0
13           can not use scrapy on Apple M1 chip     0     0     0     0     0
14                         convert text to image     1     0     0     0     0
15         calculate distance between two points     1     1     1     0     0
16              remove duplicates items in array     1     1     0     0     0
17             how to send message using telepot     1     0     0     0     0
18                         get current time zone     1     0     0     0     0
19              problem in import rest framework     1     1     0     0     0
20                         get timestamp in UNIX     1     1     1     0     0
21                   how to add column in pandas     1     0     0     0     0
22          How to set value to pandas crosstab?     1     0     0     0     0
23                     How to update a variable?     0     0     0     0     0
24                 error: fit() missing argument     0     0     0     0     0
25                  how to make a test on regex?     0     0     0     0     0
26                  try web scraping to get text     1     1     0     0     0
27                         convert int in string     1     1     1     0     0
28               Classify music according to bpm     0     0     0     0     0
29                 How to run a script on Linux?     1     0     0     0     0
30                   How to join list of strings     0     0     0     0     0
31                      How to write to csv file     1     1     1     0     0
32                count rows where column is NaN     1     1     1     0     0
33               get all index from boolean list     1     0     0     0     0
34                split on a numerical character     0     0     0     0     0
35                 sorting a multindex dataframe     0     0     0     0     0
36                         how to print variable     1     0     0     0     0
37                          sum values in column     1     1     1     0     0
38                   how to order value in array     0     0     0     0     0
39                    save image with added mask     0     0     0     0     0
40               greatest number in list of list     1     0     0     0     0
41                 how to add legend for picture     1     1     1     0     0
42               how to setup virtual enviroment     0     0     0     0     0
43     remove stopwords with regular expressions     0     0     0     0     0
44          how to use min() function for floats     0     0     0     0     0
45               how to add checkbox to a button     1     1     1     0     0
46  importing a pygame event into another script     0     0     0     0     0
47               pip install web3 is not working     1     1     1     0     0
48              parsing data from XML into excel     1     0     0     0     0
49                               how to get ssid     0     0     0     0     0

In [19]:
final_results_w2v = create_evaluation_table(w2v_test_results, test_stack_w2v_evaluated)
final_results_w2v

   Res1 Res2 Res3 Res4 Res5                                       queries
0    fp   tp   tp   tp   tp         Using IF function in Pandas dataframe
1    tn   tn   tn   tn   tn      How to send WhatsApp message each minute
2    fp   tn   tn   tn   tn     Parsing a JSON list into a normal string?
3    tn   tn   tn   tn   tn                     how to get version python
4    tp   tp   tp   fp   fp           Combining multiple columns into one
5    fn   tn   fn   tn   fn            extracting features from dataframe
6    tn   tn   tn   tn   tn                        Grouping NLTK entities
7    fp   tp   fp   tn   tn         delete a list from collection of list
8    tn   tn   fn   tn   fn                           get api google maps
9    tn   fn   tn   tn   tn           add guassian noise to a numpy array
10   tn   fn   fn   tn   tn            unable to establish SSL connection
11   tp   tp   tp   tp   tp                  create new project in django
12   fp   fp   tp   fp   fp                  can not pip install a branch
13   tn   tn   tn   tn   tn           can not use scrapy on Apple M1 chip
14   fp   tn   tn   tn   tn                         convert text to image
15   tp   tp   tp   fp   fn         calculate distance between two points
16   fp   tp   tn   tn   tn              remove duplicates items in array
17   tn   tn   tn   tn   tn             how to send message using telepot
18   fn   fn   fn   fn   fn                         get current time zone
19   fn   fn   fn   fn   fn              problem in import rest framework
20   tp   tp   tp   fn   fn                         get timestamp in UNIX
21   tp   tp   tp   fp   tp                   how to add column in pandas
22   fp   fp   fp   fp   fp          How to set value to pandas crosstab?
23   tn   fn   tn   fn   tn                     How to update a variable?
24   fn   fn   fn   tn   tn                 error: fit() missing argument
25   tn   tn   tn   tn   tn                  how to make a test on regex?
26   tp   fn   fn   fn   fn                  try web scraping to get text
27   fp   tp   fp   fp   fp                         convert int in string
28   tn   tn   tn   tn   tn               Classify music according to bpm
29   fn   tn   tn   tn   fn                 How to run a script on Linux?
30   tp   fp   fp   fp   fp                   How to join list of strings
31   tp   tp   tp   tp   tp                      How to write to csv file
32   fp   tp   fp   fp   tp                count rows where column is NaN
33   fn   fn   fn   tn   tn               get all index from boolean list
34   tn   tn   tn   tn   tn                split on a numerical character
35   tp   tp   fp   fp   tp                 sorting a multindex dataframe
36   fp   tn   fn   fn   tn                         how to print variable
37   fp   tp   tp   tp   tp                          sum values in column
38   tn   tn   tn   tn   tn                   how to order value in array
39   fn   tn   tn   fn   tn                    save image with added mask
40   fp   fp   fp   fp   tp               greatest number in list of list
41   fn   tn   tn   tn   tn                 how to add legend for picture
42   fn   fn   fn   tn   tn               how to setup virtual enviroment
43   fp   tn   tn   tn   tn     remove stopwords with regular expressions
44   tn   tn   tn   tn   tn          how to use min() function for floats
45   fp   tn   tn   tn   tn               how to add checkbox to a button
46   tn   tn   tn   tn   tn  importing a pygame event into another script
47   fp   fp   fp   fp   fp               pip install web3 is not working
48   fp   fn   fn   fn   tn              parsing data from XML into excel
49   tn   tn   tn   tn   tn                               how to get ssid

In [20]:
final_results_tfidf = create_evaluation_table(tfidf_test_results, test_stack_tfidf_evaluated)
final_results_tfidf

   Res1 Res2 Res3 Res4 Res5                                       queries
0    fp   fn   tn   tn   tn         Using IF function in Pandas dataframe
1    tn   tn   tn   tn   fn      How to send WhatsApp message each minute
2    tn   fn   tn   tn   tn     Parsing a JSON list into a normal string?
3    tn   tn   tn   tn   tn                     how to get version python
4    tn   tn   fn   fn   fn           Combining multiple columns into one
5    tn   tn   tn   tn   tn            extracting features from dataframe
6    tn   tn   tn   tn   tn                        Grouping NLTK entities
7    fn   tn   tn   tn   tn         delete a list from collection of list
8    tp   fn   tn   tn   tn                           get api google maps
9    tn   tn   tn   tn   tn           add guassian noise to a numpy array
10   fn   fn   tn   tn   tn            unable to establish SSL connection
11   fn   fn   tn   tn   tn                  create new project in django
12   tp   tn   tn   tn   tn                  can not pip install a branch
13   tn   tn   tn   tn   tn           can not use scrapy on Apple M1 chip
14   fp   tn   tn   tn   tn                         convert text to image
15   tp   fp   tp   fn   tn         calculate distance between two points
16   fp   fp   tn   tn   tn              remove duplicates items in array
17   fp   tn   tn   tn   tn             how to send message using telepot
18   tp   tn   tn   fn   tn                         get current time zone
19   tp   tp   tn   tn   fn              problem in import rest framework
20   fp   tp   tp   fn   fn                         get timestamp in UNIX
21   tp   tn   tn   tn   fn                   how to add column in pandas
22   tp   tn   tn   tn   tn          How to set value to pandas crosstab?
23   tn   tn   fn   tn   tn                     How to update a variable?
24   tn   tn   tn   tn   tn                 error: fit() missing argument
25   tn   tn   tn   tn   tn                  how to make a test on regex?
26   fp   tp   fn   fn   fn                  try web scraping to get text
27   fp   fp   fp   tn   tn                         convert int in string
28   tn   tn   tn   tn   tn               Classify music according to bpm
29   tp   tn   tn   tn   tn                 How to run a script on Linux?
30   tn   tn   tn   tn   tn                   How to join list of strings
31   tp   tp   tp   fn   fn                      How to write to csv file
32   tp   fp   fp   tn   tn                count rows where column is NaN
33   fp   tn   tn   tn   tn               get all index from boolean list
34   tn   tn   tn   tn   tn                split on a numerical character
35   tn   tn   tn   tn   tn                 sorting a multindex dataframe
36   tp   tn   fn   tn   fn                         how to print variable
37   tp   fp   tp   tn   tn                          sum values in column
38   tn   tn   tn   tn   fn                   how to order value in array
39   fn   fn   fn   tn   tn                    save image with added mask
40   tp   fn   tn   tn   tn               greatest number in list of list
41   fp   fp   fp   tn   tn                 how to add legend for picture
42   tn   tn   tn   tn   fn               how to setup virtual enviroment
43   tn   tn   fn   fn   tn     remove stopwords with regular expressions
44   tn   tn   tn   tn   tn          how to use min() function for floats
45   fp   fp   fp   tn   tn               how to add checkbox to a button
46   tn   tn   tn   tn   tn  importing a pygame event into another script
47   fp   fp   fp   tn   tn               pip install web3 is not working
48   tp   tn   tn   tn   tn              parsing data from XML into excel
49   fn   tn   tn   tn   tn                               how to get ssid

In [21]:
conf_matrix_w2v,precision_w2v,recall_w2v,f1score_w2v = create_confusion_matrix(final_results_w2v)

print('Precision w2v: ' + str(precision_w2v) + '\t')
print('Recall w2v: ' + str(recall_w2v) + '\t')
print('F1 score w2v: ' + str(f1score_w2v) + '\t')
print('\n')
conf_matrix_w2v

Precision w2v: 0.48314606741573035
Recall w2v: 0.48314606741573035
F1 score w2v: 0.48314606741573035

               Relevant  Non_relevant
Retrieved            43            46
Not_retrieved        46           115

In [22]:
conf_matrix_tfidf,precision_tfidf,recall_tfidf,f1score_tfidf = create_confusion_matrix(final_results_tfidf)

print('Precision tfidf: ' + str(precision_tfidf) + '\t')
print('Recall tfidf: ' + str(recall_tfidf) + '\t')
print('F1 score tfidf: ' + str(f1score_tfidf) + '\t')
print('\n')
conf_matrix_tfidf

Precision tfidf: 0.4782608695652174
Recall tfidf: 0.38596491228070173
F1 score tfidf: 0.42718446601941745

               Relevant  Non_relevant
Retrieved            22            24
Not_retrieved        35           169

MAP METRIC

Gives a single metric that represents the complex Area under the Precision-Recall curve. This provides the average precision per list.
Handles the ranking of lists recommended items naturally. This is in contrast to metrics that considering the retrieved items as sets.
This metric is able to give more weight to errors that happen high up in the recommended lists. Conversely, it gives less weight to errors that happens deeper in the recommended lists. This matches the need to show as many relevant items as possible high up the recommended list.

In [6]:
#funzione che prende in ingresso una riga con valori ad 1 dove è stato trovato un match
#e NaN dove no
#Calcolo l'average precision per ciascuna riga
def average_precision(row):
    
    #res1 = row['tfidf_res1']
    #res2 = row['tfidf_res2']
    #res3 = row['tfidf_res3']
    
    res1 = row.iloc[0]
    res2 = row.iloc[1]
    res3 = row.iloc[2]
    res4 = row.iloc[3]
    res5 = row.iloc[4]
    
        
    if math.isnan(res1) and math.isnan(res2) and math.isnan(res3) and math.isnan(res4) and math.isnan(res5):
        
        
        return 0
    
    else:
        #La i tiene conto dei risultati rilevanti
        i = 1
        #la j tiene conto del totale dei risultati esaminati 
        j = 1
        numerator = 0 
        
        for el in row:
            if el == 1:
                numerator = numerator + (i/j)
                i = i+1
            j = j+1
            
        avg_precision = numerator/i
        
        return avg_precision

In [7]:
#Funzione che calcola il valore della metrica map al quale passare le colonne relative ai test in ordine di indice
def calculate_map(test_results):
 
    #test_results = test_results[['tfidf_res1', 'tfidf_res2','tfidf_res3']]
    avg_prec = 0 
    n_test = len(test_results)
    
    print('Number of test record:' + str(n_test) + '\n')
    
    for index, row in test_results.iterrows():
        avg_prec = avg_prec + average_precision(row)
        
        
    map_value = avg_prec/n_test
    
    return map_value

In [23]:
map_value_tfidf = calculate_map(test_stack[['tfidf_res1', 'tfidf_res2','tfidf_res3','tfidf_res4','tfidf_res5']]) 

print('Map value for tfidf: ' + str(map_value_tfidf))

Number of test record:50

Map value for tfidf: 0.27565

In [14]:
map_value_w2v = calculate_map(test_stack[['w2v_res1', 'w2v_res2','w2v_res3','w2v_res4','w2v_res5']]) 

print('Map value for w2v: ' + str(map_value_w2v))

Number of test record:50

Map value for w2v: 0.34160555555555566